version: '3.8'

services:
  nginx:
    image: nginx:alpine
    depends_on: 
      - auth_module
      - web_app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/weball.conf.template:/etc/nginx/templates/weball.conf.template
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    environment:
      TEST_SUBDOMAIN: ${TEST_SUBDOMAIN}
    command: nginx -g 'daemon off;'
    restart: unless-stopped
    networks:
      - nginx-net
    
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL_FOR_SSL} --agree-tos --no-eff-email -d ${TEST_SUBDOMAIN}
    networks:
      - nginx-net
       
  redis_web:
    image: redis:8.4.0-alpine
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - red-web
      - tg-net  # Добавляем сеть для tg_core

  web_app:
    depends_on:
      redis_web:
        condition: service_healthy
    build: src/web_module
    restart: unless-stopped
    networks:
      - red-web
      - nginx-net

  tg_core:
    build: src/tg_bot_module
    restart: unless-stopped
    depends_on:
      redis_web:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      - TOKEN=${TOKEN}
      - REDIS_HOST=redis_web  # Явно указываем имя хоста
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=poll_system
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    networks:
      - tg-net  # Сеть для подключения к Redis
      - db-net  # Сеть для подключения к PostgreSQL
      - mongo-net  # Сеть для подключения к MongoDB

  postgres:
    image: postgres:18.1-alpine3.23
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: poll_system
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db-net

  sql_module:
    build: src/sql_module
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - db-net
    environment:
      DATABASE_URL: host=postgres user=postgres password=${POSTGRES_PASSWORD} dbname=poll_system sslmode=disable  # Исправлено: postgres вместо postgres-db
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mongo-net
    volumes:
      - mongodb_data:/data/db

  auth_module:
    build: src/auth_module
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017  # Исправлено: mongodb вместо mongo
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID}
      YANDEX_CLIENT_SECRET: ${YANDEX_CLIENT_SECRET}
    networks:
      - mongo-net
      - nginx-net

networks:
  db-net:
    driver: bridge
  red-web:
    driver: bridge
  mongo-net:
    driver: bridge
  nginx-net:
    driver: bridge
  tg-net:  # Новая сеть для tg_core
    driver: bridge

volumes:
  mongodb_data:
  etc-letsencrypt:
  www-html: